global using Dotnet9.BlazorWebApp;
global using System.Text.Encodings.Web;
global using System.Text.Unicode;
global using Dotnet9.Caller;
global using Dotnet9.Contracts.Dto;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using Dotnet9.BlazorWebApp.Services;
global using Dotnet9.Contracts.Dto.Blogs;