import { Math } from '@vicons/tabler';
import { defineTool } from '../tool';

export const tool = defineTool({
  name: '数学计算器',
  path: '/math-evaluator',
  description: '数学表达式计算，您可以使用sqrt，cos，sin，abs等函数-（A calculator for evaluating mathematical expressions. You can use functions like sqrt, cos, sin, abs, etc.)）',
  keywords: [
    'math',
    'evaluator',
    'calculator',
    'expression',
    'abs',
    'acos',
    'acosh',
    'acot',
    'acoth',
    'acsc',
    'acsch',
    'asec',
    'asech',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'cos',
    'cosh',
    'cot',
    'coth',
    'csc',
    'csch',
    'sec',
    'sech',
    'sin',
    'sinh',
    'sqrt',
    'tan',
    'tanh',
  ],
  component: () => import('./math-evaluator.vue'),
  icon: Math,
});
