import { Math } from '@vicons/tabler';
import { defineTool } from '../tool';

export const tool = defineTool({
  name: '数学计算器',
  path: '/math-evaluator',
  description: '执行数学表达式，就像执行计算器一样（您可以使用sqrt，cos，sin，abs等函数...（Evaluate math expression, like a calculator on steroid (you can use function like sqrt, cos, sin, abs, ...)）',
  keywords: [
    'math',
    'evaluator',
    'acos',
    'acosh',
    'acot',
    'acoth',
    'acsc',
    'acsch',
    'asec',
    'asech',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'cos',
    'cosh',
    'cot',
    'coth',
    'csc',
    'csch',
    'sec',
    'sech',
    'sin',
    'sinh',
    'tan',
    'tanh',
  ],
  component: () => import('./math-evaluator.vue'),
  icon: Math,
});
