/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreationType } from './creation-type';
import { TagsOutput } from './tags-output';
/**
 * 
 * @export
 * @interface ArticleOutput
 */
export interface ArticleOutput {
    /**
     * 文章ID
     * @type {number}
     * @memberof ArticleOutput
     */
    id?: number;
    /**
     * 标题
     * @type {string}
     * @memberof ArticleOutput
     */
    title?: string | null;
    /**
     * 栏目ID
     * @type {number}
     * @memberof ArticleOutput
     */
    categoryId?: number;
    /**
     * 栏目名称
     * @type {string}
     * @memberof ArticleOutput
     */
    categoryName?: string | null;
    /**
     * 是否置顶
     * @type {boolean}
     * @memberof ArticleOutput
     */
    isTop?: boolean;
    /**
     * 
     * @type {CreationType}
     * @memberof ArticleOutput
     */
    creationType?: CreationType;
    /**
     * 简介
     * @type {string}
     * @memberof ArticleOutput
     */
    summary?: string | null;
    /**
     * 封面图
     * @type {string}
     * @memberof ArticleOutput
     */
    cover?: string | null;
    /**
     * 发布时间
     * @type {Date}
     * @memberof ArticleOutput
     */
    publishTime?: Date;
    /**
     * 标签
     * @type {Array<TagsOutput>}
     * @memberof ArticleOutput
     */
    tags?: Array<TagsOutput> | null;
}
