/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CategoryOutput
 */
export interface CategoryOutput {
    /**
     * 栏目ID
     * @type {number}
     * @memberof CategoryOutput
     */
    id?: number;
    /**
     * 父级ID
     * @type {number}
     * @memberof CategoryOutput
     */
    parentId?: number | null;
    /**
     * 排序
     * @type {number}
     * @memberof CategoryOutput
     */
    sort?: number;
    /**
     * 栏目名称
     * @type {string}
     * @memberof CategoryOutput
     */
    name?: string | null;
    /**
     * 文章条数
     * @type {number}
     * @memberof CategoryOutput
     */
    total?: number;
}
