/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * <br />&nbsp;原创 Original = 0<br />&nbsp;转载 Reprinted = 1<br />
 * @export
 * @enum {string}
 */
export enum CreationType {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

