/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface OAuthAccountDetailOutput
 */
export interface OAuthAccountDetailOutput {
    /**
     * 用户ID
     * @type {number}
     * @memberof OAuthAccountDetailOutput
     */
    id?: number;
    /**
     * 昵称
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    nickName?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    avatar?: string | null;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof OAuthAccountDetailOutput
     */
    status?: AvailabilityStatus;
    /**
     * 网站链接
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    link?: string | null;
    /**
     * logo
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    logo?: string | null;
    /**
     * 网站名称
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    siteName?: string | null;
    /**
     * 对方博客友链地址
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    url?: string | null;
    /**
     * 网站介绍
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    remark?: string | null;
}
