/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ReplyOutput
 */
export interface ReplyOutput {
  /**
   * 评论ID
   * @type {number}
   * @memberof ReplyOutput
   */
  id?: number;
  /**
   * 评论内容
   * @type {string}
   * @memberof CommentOutput
   */
  content?: string | null;
  /**
   * 顶级楼层评论ID
   * @type {number}
   * @memberof ReplyOutput
   */
  rootId?: number | null;
  /**
   * 上级评论ID
   * @type {number}
   * @memberof ReplyOutput
   */
  parentId?: number | null;
  /**
   * 当前评论人ID
   * @type {number}
   * @memberof ReplyOutput
   */
  accountId?: number;
  /**
   * 回复人ID
   * @type {number}
   * @memberof ReplyOutput
   */
  replyAccountId?: number | null;
  /**
   * 博主标识
   */
  isBlogger?: boolean;
  /**
   * 当前人昵称
   * @type {string}
   * @memberof ReplyOutput
   */
  nickName?: string | null;
  /**
   * 回复人昵称
   * @type {string}
   * @memberof ReplyOutput
   */
  relyNickName?: string | null;
  /**
   * 当前评论人头像
   * @type {string}
   * @memberof ReplyOutput
   */
  avatar?: string | null;
  /**
   * Ip地址
   * @type {string}
   * @memberof ReplyOutput
   */
  ip?: string | null;
  /**
   * Ip所属地
   * @type {string}
   * @memberof ReplyOutput
   */
  geolocation?: string | null;
  /**
   * 点赞数量
   * @type {number}
   * @memberof CommentOutput
   */
  praiseTotal?: number;
  /**
   * 是否已点赞
   * @type {boolean}
   * @memberof CommentOutput
   */
  isPraise?: boolean;
  /**
   * 评论时间
   * @type {Date}
   * @memberof ReplyOutput
   */
  createdTime?: Date;
}
