/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TagsOutput
 */
export interface TagsOutput {
    /**
     * 标签ID
     * @type {number}
     * @memberof TagsOutput
     */
    id?: number;
    /**
     * 图标
     * @type {string}
     * @memberof TagsOutput
     */
    icon?: string | null;
    /**
     * 标签名称
     * @type {string}
     * @memberof TagsOutput
     */
    name?: string | null;
    /**
     * 颜色
     * @type {string}
     * @memberof TagsOutput
     */
    color?: string | null;
}
