global using Dotnet9.WebShare;
global using System.Text;
global using Dotnet9.Caller.Services.Blogs;
global using Dotnet9.Commons;
global using Dotnet9.WebShare.Services;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using System.Net.Mime;
global using Dotnet9.Caller.Services.Systems;