// const domain = "https://oss.37czone.com/emoji/";
const domain = "/emoji/";
const emoji: Record<string, string> = {
  "[18禁]": domain + "18jin" + ".png",
  "[爱慕]": domain + "aimu" + ".png",
  "[白眼]": domain + "baiyan" + ".png",
  "[闭嘴]": domain + "bizui" + ".png",
  "[擦汗]": domain + "cahan" + ".png",
  "[大无语]": domain + "daiwugu" + ".png",
  "[大金牙]": domain + "dajinya" + ".png",
  "[大哭]": domain + "daku" + ".png",
  "[打脸]": domain + "dalian" + ".png",
  "[大笑]": domain + "daxiao" + ".png",
  "[得意]": domain + "deyi" + ".png",
  "[愤怒]": domain + "fanu" + ".png",
  "[飞吻]": domain + "feiwen" + ".png",
  "[奋斗]": domain + "fendou" + ".png",
  "[尬笑]": domain + "gaxiao" + ".png",
  "[害羞]": domain + "haixiu" + ".png",
  "[憨笑]": domain + "hanxiao" + ".png",
  "[哈欠]": domain + "haqian" + ".png",
  "[互粉]": domain + "hufen" + ".png",
  "[奸笑]": domain + "jianxiao" + ".png",
  "[惊喜]": domain + "jingxi" + ".png",
  "[机智]": domain + "jizhi" + ".png",
  "[看]": domain + "kan" + ".png",
  "[可爱]": domain + "keai" + ".png",
  "[可怜]": domain + "kelian" + ".png",
  "[恐惧]": domain + "kongju" + ".png",
  "[抠鼻]": domain + "koubi" + ".png",
  "[快哭了]": domain + "kuaikule" + ".png",
  "[困]": domain + "kun" + ".png",
  "[酷拽]": domain + "kuzhuai" + ".png",
  "[泪奔]": domain + "leiben" + ".png",
  "[灵光一闪]": domain + "lingguangyishan" + ".png",
  "[流泪]": domain + "liulei" + ".png",
  "[绿帽子]": domain + "lvmaozi" + ".png",
  "[OK]": domain + "ok.jpg",
  "[马思纯的微笑]": domain + "masichundeweixiao" + ".png",
  "[玫瑰]": domain + "meigui" + ".png",
  "[摸头]": domain + "motou" + ".png",
  "[撇嘴]": domain + "piezui" + ".png",
  "[钱]": domain + "qian" + ".png",
  "[强]": domain + "qiang" + ".png",
  "[敲打]": domain + "qiaoda" + ".png",
  "[泣不成声]": domain + "qibuchengsheng" + ".png",
  "[求抱抱]": domain + "qiubaobao" + ".png",
  "[去污粉]": domain + "quwufen" + ".png",
  "[如花]": domain + "ruhua" + ".png",
  "[石化]": domain + "shihua" + ".png",
  "[衰]": domain + "shuai" + ".png",
  "[思考]": domain + "sikao" + ".png",
  "[酸了]": domain + "sl.jpg",
  "[调皮]": domain + "tiaopi.jpg",
  "[听歌]": domain + "tingge" + ".png",
  "[偷笑]": domain + "touxiao" + ".png",
  "[吐]": domain + "tu" + ".png",
  "[吐彩虹]": domain + "tucaihong" + ".png",
  "[吐血]": domain + "tuxue" + ".png",
  "[v5]": domain + "v5" + ".png",
  "[微笑]": domain + "weixiao" + ".png",
  "[捂脸]": domain + "wulian" + ".png",
  "[笑]": domain + "xiao" + ".png",
  "[笑鼓掌]": domain + "xiaoguzhang" + ".png",
  "[笑哭]": domain + "xiaoku" + ".png",
  "[熊吉]": domain + "xiongji" + ".png",
  "[小瞧]": domain + "xq.jpg",
  "[嘘]": domain + "xu" + ".png",
  "[耶]": domain + "ye" + ".png",
  "[疑惑]": domain + "yh.jpg",
  "[晕]": domain + "yun" + ".png",
  "[再见]": domain + "zaijian" + ".png",
  "[炸弹]": domain + "zhadan" + ".png",
  "[震惊]": domain + "zhenjing" + ".png",
  "[支持]": domain + "zhichi.jpg",
  "[周冬雨的凝视]": domain + "zhoudongyudeningshi" + ".png",
  "[皱眉]": domain + "zhoumei" + ".png",
  "[抓狂]": domain + "zhuakuang" + ".png",
  "[紫薇别走]": domain + "ziweibiezou" + ".png",
  "[龇牙]": domain + "ziya" + ".png",
  "[做鬼脸]": domain + "zuoguilian" + ".png",
  "[左上]": domain + "zuoshang" + ".png",
};
export default emoji;
