/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PictureOutput
 */
export interface PictureOutput {
    /**
     * 图片ID
     * @type {number}
     * @memberof PictureOutput
     */
    id?: number;
    /**
     * 图片地址
     * @type {string}
     * @memberof PictureOutput
     */
    url?: string | null;
}
