/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TalkDetailOutput
 */
export interface TalkDetailOutput {
  /**
   *
   * @type {number}
   * @memberof TalkDetailOutput
   */
  id?: number;
  /**
   * 是否置顶
   * @type {boolean}
   * @memberof TalkDetailOutput
   */
  isTop?: boolean;
  /**
   * 内容
   * @type {string}
   * @memberof TalkDetailOutput
   */
  content?: string | null;
  /**
   * 图片
   * @type {string}
   * @memberof TalksOutput
   */
  images?: string | null;
  /**
   * 点赞数量
   * @type {number}
   * @memberof TalkDetailOutput
   */
  upvote?: number;
    /**
   * 是否已点赞
   * @type {boolean}
   * @memberof TalkDetailOutput
   */
    isPraise?: boolean;
  /**
   * 评论数量
   * @type {number}
   * @memberof TalkDetailOutput
   */
  comments?: number;
  /**
   * 发布时间
   * @type {Date}
   * @memberof TalkDetailOutput
   */
  createdTime?: Date;
  /**
   * 是否允许评论
   * @type {boolean}
   * @memberof TalkDetailOutput
   */
  isAllowComments?: boolean;
}
