global using Dotnet9.Commons;
global using Dotnet9.Web.Service.BlogPosts;
global using Dotnet9.Web.Service.Categories;
global using Dotnet9.Web.ViewModel.BlogPosts;
global using Dotnet9.Web.ViewModel.Categories;
global using Dotnet9.WebAPI.Domain.BlogPosts;
global using Dotnet9.WebAPI.Infrastructure;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
