/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 *
 * @export
 * @interface AddTalksInput
 */
export interface AddTalksInput {
	/**
	 * 是否置顶
	 * @type {boolean}
	 * @memberof AddTalksInput
	 */
	isTop?: boolean;
	/**
	 * 说说正文
	 * @type {string}
	 * @memberof AddTalksInput
	 */
	content: string;
    /**
	 * 说说图片
	 * @type {string}
	 * @memberof AddTalksInput
	 */
	images?: string | null;
	/**
	 * 是否允许评论
	 * @type {boolean}
	 * @memberof AddTalksInput
	 */
	isAllowComments?: boolean;
	/**
	 *
	 * @type {AvailabilityStatus}
	 * @memberof AddTalksInput
	 */
	status?: AvailabilityStatus;
}
