/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface AddFriendLinkInput
 */
export interface AddFriendLinkInput {
    /**
     * 网站名称
     * @type {string}
     * @memberof AddFriendLinkInput
     */
    siteName: string;
    /**
     * 网站链接
     * @type {string}
     * @memberof AddFriendLinkInput
     */
    link: string;
    /**
     * 网站logo
     * @type {string}
     * @memberof AddFriendLinkInput
     */
    logo: string;
    /**
     * 对方博客友链的地址
     * @type {string}
     * @memberof AddFriendLinkInput
     */
    url?: string | null;
    /**
     * 是否忽略对方站点是否存在本站链接
     * @type {boolean}
     * @memberof AddFriendLinkInput
     */
    isIgnoreCheck?: boolean;
    /**
     * 备注
     * @type {string}
     * @memberof AddFriendLinkInput
     */
    remark?: string | null;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof AddFriendLinkInput
     */
    sort: number;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof AddFriendLinkInput
     */
    status?: AvailabilityStatus;
}
