/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 *
 * @export
 * @interface AddTagInput
 */
export interface AddTagInput {
	/**
	 * 标签名称
	 * @type {string}
	 * @memberof AddTagInput
	 */
	name: string;
	/**
	 * 封面图
	 * @type {string}
	 * @memberof AddTagInput
	 */
	cover: string;
	/**
	 * 标签颜色
	 * @type {string}
	 * @memberof AddTagInput
	 */
	color?: string | null;
	/**
	 * 标签图标
	 * @type {string}
	 * @memberof AddTagInput
	 */
	icon?: string | null;
	/**
	 *
	 * @type {AvailabilityStatus}
	 * @memberof AddTagInput
	 */
	status?: AvailabilityStatus;
	/**
	 * 排序值（值越小越靠前）
	 * @type {number}
	 * @memberof AddTagInput
	 */
	sort: number;
	/**
	 * 备注
	 * @type {string}
	 * @memberof AddTagInput
	 */
	remark: number;
}
