/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface AddCustomConfigItemInput
 */
export interface AddCustomConfigItemInput {
    /**
     * 自定义配置Id
     * @type {number}
     * @memberof AddCustomConfigItemInput
     */
    configId: number;
    /**
     * 配置
     * @type {string}
     * @memberof AddCustomConfigItemInput
     */
    json: string;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof AddCustomConfigItemInput
     */
    status?: AvailabilityStatus;
}
