/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface AddCustomConfigInput
 */
export interface AddCustomConfigInput {
    /**
     * 配置名称
     * @type {string}
     * @memberof AddCustomConfigInput
     */
    name: string;
    /**
     * 配置唯一编码（类名）
     * @type {string}
     * @memberof AddCustomConfigInput
     */
    code: string;
    /**
     * 是否是多项（集合）
     * @type {boolean}
     * @memberof AddCustomConfigInput
     */
    isMultiple?: boolean;
     /**
     * 是否允许创建实体
     * @type {boolean}
     * @memberof AddCustomConfigInput
     */
     allowCreationEntity?: boolean;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof AddCustomConfigInput
     */
    status?: AvailabilityStatus;
    /**
     * 备注
     * @type {string}
     * @memberof AddCustomConfigInput
     */
    remark?: string | null;
}
