/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdminLoginInput
 */
export interface AdminLoginInput {
    /**
     * 登录名
     * @type {string}
     * @memberof AdminLoginInput
     */
    account: string;
    /**
     * 密码
     * @type {string}
     * @memberof AdminLoginInput
     */
    password: string;
    /**
     * 验证码唯一ID
     * @type {string}
     * @memberof AdminLoginInput
     */
    id: string;
    /**
     * 验证码
     * @type {string}
     * @memberof AdminLoginInput
     */
    code: string;
}
