/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface AlbumsPageOutput
 */
export interface AlbumsPageOutput {
    /**
     * 专辑ID
     * @type {number}
     * @memberof AlbumsPageOutput
     */
    id?: number;
    /**
     * 专辑名称
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    name?: string | null;
    /**
     * 专辑别名
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    slug?: string | null;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof AlbumsPageOutput
     */
    status?: AvailabilityStatus;
    /**
     * 排序
     * @type {number}
     * @memberof AlbumsPageOutput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    remark?: string | null;
    /**
     * 标签封面
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    cover?: string | null;
    /**
     * 创建时间
     * @type {Date}
     * @memberof AlbumsPageOutput
     */
    createdTime?: Date;
}
