/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
import { CreationType } from './creation-type';
/**
 *
 * @export
 * @interface ArticleDetailOutput
 */
export interface ArticleDetailOutput {
	/**
	 * 文章ID
	 * @type {number}
	 * @memberof ArticleDetailOutput
	 */
	id?: number;
	/**
	 * 标题
	 * @type {string}
	 * @memberof ArticleDetailOutput
	 */
	title?: string | null;
	/**
	 * 简介
	 * @type {string}
	 * @memberof ArticleDetailOutput
	 */
	summary?: string | null;
	/**
	 * 封面
	 * @type {string}
	 * @memberof ArticleDetailOutput
	 */
	cover?: string | null;
	/**
	 *
	 * @type {AvailabilityStatus}
	 * @memberof ArticleDetailOutput
	 */
	status?: AvailabilityStatus;
	/**
	 * 原文地址
	 * @type {string}
	 * @memberof ArticleDetailOutput
	 */
	link?: string | null;
	/**
	 * 是否置顶
	 * @type {boolean}
	 * @memberof ArticleDetailOutput
	 */
	isTop?: boolean;
	/**
	 * 排序
	 * @type {number}
	 * @memberof ArticleDetailOutput
	 */
	sort?: number;
	/**
	 * 作者
	 * @type {string}
	 * @memberof ArticleDetailOutput
	 */
	author?: string | null;
	/**
	 * 文章内容
	 * @type {string}
	 * @memberof ArticleDetailOutput
	 */
	content?: string | null;
	/**
	 * 是否允许评论
	 * @type {boolean}
	 * @memberof ArticleDetailOutput
	 */
	isAllowComments?: boolean;
	/**
	 * 是个是HTML
	 * @type {boolean}
	 * @memberof ArticleDetailOutput
	 */
	isHtml?: boolean;
	/**
	 *
	 * @type {CreationType}
	 * @memberof ArticleDetailOutput
	 */
	creationType?: CreationType;
	/**
	 * 过期时间（过期后文章不显示）
	 * @type {Date}
	 * @memberof ArticleDetailOutput
	 */
	expiredTime?: Date | null;
	/**
	 * 发布时间
	 * @type {Date}
	 * @memberof ArticleDetailOutput
	 */
	publishTime?: Date | null;
	/**
	 * 标签
	 * @type {Array<number>}
	 * @memberof ArticleDetailOutput
	 */
	tags?: Array<number> | null;
	/**
	 * 栏目ID
	 * @type {number}
	 * @memberof ArticleDetailOutput
	 */
	categoryId?: number | null;
}
