/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface AvailabilityDto
 */
export interface AvailabilityDto {
    /**
     * 主键
     * @type {number}
     * @memberof AvailabilityDto
     */
    id?: number;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof AvailabilityDto
     */
    status?: AvailabilityStatus;
}
