/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 可用状态<br />&nbsp;启用 Enable = 0<br />&nbsp;禁用 Disable = 1<br />
 * @export
 * @enum {string}
 */
export enum AvailabilityStatus {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

