/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
import { CategoryPageOutput } from './category-page-output';
/**
 * 
 * @export
 * @interface CategoryPageOutput
 */
export interface CategoryPageOutput {
    /**
     * 栏目ID
     * @type {number}
     * @memberof CategoryPageOutput
     */
    id?: number;
    /**
     * 栏目名称
     * @type {string}
     * @memberof CategoryPageOutput
     */
    name?: string | null;
    /**
     * 父级id
     * @type {number}
     * @memberof CategoryPageOutput
     */
    parentId?: number | null;
    /**
     * 封面图
     * @type {string}
     * @memberof CategoryPageOutput
     */
    cover?: string | null;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof CategoryPageOutput
     */
    status?: AvailabilityStatus;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof CategoryPageOutput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof CategoryPageOutput
     */
    remark?: string | null;
    /**
     * 创建时间
     * @type {Date}
     * @memberof CategoryPageOutput
     */
    createdTime?: Date;
    /**
     * 子栏目
     * @type {Array<CategoryPageOutput>}
     * @memberof CategoryPageOutput
     */
    children?: Array<CategoryPageOutput> | null;
}
