/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 博客封面类型<br />&nbsp;首页封面图 Home = 0<br />&nbsp;归档封面图 Archives = 1<br />&nbsp;分类封面图 Category = 2<br />&nbsp;标签封面图 Tag = 3<br />&nbsp;模块封面图 Cover = 4<br />&nbsp;说说封面图 Talk = 5<br />&nbsp;关于封面图 About = 6<br />&nbsp;留言封面图 Message = 7<br />&nbsp;个人中心封面图 User = 8<br />
 * @export
 * @enum {string}
 */
export enum CoverType {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8
}

