/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
import { CoverType } from './cover-type';
/**
 * 
 * @export
 * @interface CoversPageOutput
 */
export interface CoversPageOutput {
    /**
     * 模块封面ID
     * @type {number}
     * @memberof CoversPageOutput
     */
    id?: number;
    /**
     * 名称
     * @type {string}
     * @memberof CoversPageOutput
     */
    name?: string | null;
    /**
     * 
     * @type {CoverType}
     * @memberof CoversPageOutput
     */
    type?: CoverType;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof CoversPageOutput
     */
    status?: AvailabilityStatus;
    /**
     * 是否显示
     * @type {boolean}
     * @memberof CoversPageOutput
     */
    isVisible?: boolean;
    /**
     * 排序
     * @type {number}
     * @memberof CoversPageOutput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof CoversPageOutput
     */
    remark?: string | null;
    /**
     * 封面
     * @type {string}
     * @memberof CoversPageOutput
     */
    cover?: string | null;
    /**
     * 创建时间
     * @type {Date}
     * @memberof CoversPageOutput
     */
    createdTime?: Date;
}
