/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * <br />&nbsp;原创 Original = 0<br />&nbsp;投稿 Contributes = 1<br />&nbsp;转载 Reprinted = 2<br />
 * @export
 * @enum {string}
 */
export enum CreationType {
    Original = 'Original',
    Contributes = 'Contributes',
    Reprinted = 'Reprinted'
}

