/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface CustomConfigPageOutput
 */
export interface CustomConfigPageOutput {
    /**
     * 自定义配置Id
     * @type {number}
     * @memberof CustomConfigPageOutput
     */
    id?: number;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof CustomConfigPageOutput
     */
    status?: AvailabilityStatus;
    /**
     * 备注
     * @type {string}
     * @memberof CustomConfigPageOutput
     */
    remark?: string | null;
    /**
     * 配置名称
     * @type {string}
     * @memberof CustomConfigPageOutput
     */
    name?: string | null;
    /**
     * 唯一编码
     * @type {string}
     * @memberof CustomConfigPageOutput
     */
    code?: string | null;
    /**
     * 是否是多项配置
     * @type {boolean}
     * @memberof CustomConfigPageOutput
     */
    isMultiple?: boolean;
    /**
     * 是否已生成实体
     * @type {boolean}
     * @memberof CustomConfigPageOutput
     */
    isGenerate?: boolean;
      /**
     * 是否允许创建实体
     * @type {boolean}
     * @memberof CustomConfigPageOutput
     */
      allowCreationEntity?: boolean;
    /**
     * 创建时间
     * @type {Date}
     * @memberof CustomConfigPageOutput
     */
    createdTime?: Date;
}
