/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CustomConfigDetailOutput
 */
export interface CustomConfigDetailOutput {
	/**
	 * 表单渲染Json
	 * @type {{ [key: string]: JToken; }}
	 * @memberof CustomConfigDetailOutput
	 */
	formJson?: Record<string, any> | null;
	/**
	 * 表单数据
	 * @type {{ [key: string]: JToken; }}
	 * @memberof CustomConfigDetailOutput
	 */
	dataJson?: Record<string, any> | null;

	/**
	 * 配置项Id
	 * @type {{ string }}
	 * @memberof CustomConfigDetailOutput
	 */
	itemId?: number | null;
}
