/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JToken } from './jtoken';
/**
 * 
 * @export
 * @interface CustomConfigSetJsonInput
 */
export interface CustomConfigSetJsonInput {
    /**
     * 自定义配置ID
     * @type {number}
     * @memberof CustomConfigSetJsonInput
     */
    id: number;
    /**
     * 表单设计
     * @type {{ [key: string]: JToken; }}
     * @memberof CustomConfigSetJsonInput
     */
    json: { [key: string]: JToken; };
}
