/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LogLevel } from './log-level';
/**
 *
 * @export
 * @interface OperationLogPageOutput
 */
export interface OperationLogPageOutput {
	/**
	 * 日志ID
	 * @type {number}
	 * @memberof OperationLogPageOutput
	 */
	id?: number;
	/**
	 * 日志描述
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	description?: string | null;
	/**
	 *
	 * @type {LogLevel}
	 * @memberof OperationLogPageOutput
	 */
	logLevel?: LogLevel;
	/**
	 * 日志详细信息
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	message?: string | null;
	/**
	 * 路由名称
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	actionName?: string | null;
	/**
	 * 控制器名称
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	controllerName?: string | null;
	/**
	 * 请求方式
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	httpMethod?: string | null;
	/**
	 * 状态码
	 * @type {number}
	 * @memberof OperationLogPageOutput
	 */
	httpStatusCode?: number;
	/**
	 * 耗时（毫秒）
	 * @type {number}
	 * @memberof OperationLogPageOutput
	 */
	elapsed?: number;
	/**
	 * 异常信息
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	exception?: string | null;
	/**
	 * 地理位置
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	location?: string | null;
	/**
	 * ip地址
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	remoteIp?: string | null;
	/**
	 * 客户端系统信息
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	osDescription?: string | null;
	/**
	 * 浏览器
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	userAgent?: string | null;
	/**
	 * 请求参数
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	parameter?: string | null;
	/**
	 * 响应参数
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	response?: string | null;
	/**
	 * 请求地址
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	requestUrl?: string | null;
	/**
	 * 操作人
	 * @type {string}
	 * @memberof OperationLogPageOutput
	 */
	account?: string | null;
	/**
	 * 创建时间
	 */
	createdTime: Date;
}
