/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RouterMetaOutput } from './router-meta-output';
import { RouterOutput } from './router-output';
/**
 * 
 * @export
 * @interface RouterOutput
 */
export interface RouterOutput {
    /**
     * 路由名称
     * @type {string}
     * @memberof RouterOutput
     */
    name?: string | null;
    /**
     * 路由地址
     * @type {string}
     * @memberof RouterOutput
     */
    path?: string | null;
    /**
     * 组件
     * @type {string}
     * @memberof RouterOutput
     */
    component?: string | null;
    /**
     * 
     * @type {RouterMetaOutput}
     * @memberof RouterOutput
     */
    meta?: RouterMetaOutput;
    /**
     * 子菜单
     * @type {Array<RouterOutput>}
     * @memberof RouterOutput
     */
    children?: Array<RouterOutput> | null;
}
