/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MenuType } from './menu-type';
/**
 * 
 * @export
 * @interface RouterMetaOutput
 */
export interface RouterMetaOutput {
    /**
     * 标题
     * @type {string}
     * @memberof RouterMetaOutput
     */
    title?: string | null;
    /**
     * 外链
     * @type {string}
     * @memberof RouterMetaOutput
     */
    isLink?: string | null;
    /**
     * 是否隐藏
     * @type {boolean}
     * @memberof RouterMetaOutput
     */
    isHide?: boolean;
    /**
     * 是否缓存
     * @type {boolean}
     * @memberof RouterMetaOutput
     */
    isKeepAlive?: boolean;
    /**
     * 是否固定
     * @type {boolean}
     * @memberof RouterMetaOutput
     */
    isAffix?: boolean;
    /**
     * 菜单
     * @type {string}
     * @memberof RouterMetaOutput
     */
    icon?: string | null;
    /**
     * 
     * @type {MenuType}
     * @memberof RouterMetaOutput
     */
    type?: MenuType;
}
