/* tslint:disable */
/* eslint-disable */
/**
 * 后端接口
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SigninLogPageOutput
 */
export interface SigninLogPageOutput {
    /**
     * 日志ID
     * @type {number}
     * @memberof SigninLogPageOutput
     */
    id?: number;
    /**
     * 消息
     * @type {string}
     * @memberof SigninLogPageOutput
     */
    message?: string | null;
    /**
     * ip地址
     * @type {string}
     * @memberof SigninLogPageOutput
     */
    remoteIp?: string | null;
    /**
     * 地理位置
     * @type {string}
     * @memberof SigninLogPageOutput
     */
    location?: string | null;
    /**
     * 客户端系统信息
     * @type {string}
     * @memberof SigninLogPageOutput
     */
    osDescription?: string | null;
    /**
     * 客户端浏览器信息
     * @type {string}
     * @memberof SigninLogPageOutput
     */
    userAgent?: string | null;
    /**
     * 登录时间
     * @type {Date}
     * @memberof SigninLogPageOutput
     */
    createdTime?: Date;
    /**
     * 登录人账户名
     * @type {string}
     * @memberof SigninLogPageOutput
     */
    account?: string | null;
}
