/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
import { SysOrgPageOutput } from './sys-org-page-output';
/**
 * 
 * @export
 * @interface SysOrgPageOutput
 */
export interface SysOrgPageOutput {
    /**
     * 组织机构Id
     * @type {number}
     * @memberof SysOrgPageOutput
     */
    id?: number;
    /**
     * 父级Id
     * @type {number}
     * @memberof SysOrgPageOutput
     */
    parentId?: number | null;
    /**
     * 部门名称
     * @type {string}
     * @memberof SysOrgPageOutput
     */
    name?: string | null;
    /**
     * 部门编码
     * @type {string}
     * @memberof SysOrgPageOutput
     */
    code?: string | null;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof SysOrgPageOutput
     */
    status?: AvailabilityStatus;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof SysOrgPageOutput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof SysOrgPageOutput
     */
    remark?: string | null;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysOrgPageOutput
     */
    createdTime?: Date;
    /**
     * 
     * @type {Array<SysOrgPageOutput>}
     * @memberof SysOrgPageOutput
     */
    children?: Array<SysOrgPageOutput> | null;
}
