/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 *
 * @export
 * @interface TalksPageOutput
 */
export interface TalksPageOutput {
	/**
	 * 主键
	 * @type {number}
	 * @memberof TalksPageOutput
	 */
	id?: number;
	/**
	 *  状态
	 * @type {AvailabilityStatus}
	 * @memberof TalksPageOutput
	 */
	status?: AvailabilityStatus;
	/**
	 *  内容
	 * @type {string}
	 * @memberof TalksPageOutput
	 */
	content?: string | null;
	/**
	 *  图片
	 * @type {string}
	 * @memberof TalksPageOutput
	 */
	images?: string | null;
	/**
	 *  是否允许评论
	 * @type {boolean}
	 * @memberof TalksPageOutput
	 */
	isAllowComments?: boolean;
	/**
	 *  是否置顶
	 * @type {boolean}
	 * @memberof TalksPageOutput
	 */
	isTop?: boolean;
	/**
	 *  发布时间
	 * @type {Date}
	 * @memberof TalksPageOutput
	 */
	createdTime?: Date;
}
