/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TreeSelectOutput } from './tree-select-output';
/**
 * 树形下拉框
 * @export
 * @interface TreeSelectOutput
 */
export interface TreeSelectOutput {
    /**
     * 文本
     * @type {string}
     * @memberof TreeSelectOutput
     */
    label?: string | null;
    /**
     * 值
     * @type {number}
     * @memberof TreeSelectOutput
     */
    value?: number;
    /**
     * 子选项
     * @type {Array<TreeSelectOutput>}
     * @memberof TreeSelectOutput
     */
    children?: Array<TreeSelectOutput> | null;
}
