/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface UpdateOrgInput
 */
export interface UpdateOrgInput {
    /**
     * 父级Id
     * @type {number}
     * @memberof UpdateOrgInput
     */
    parentId?: number | null;
    /**
     * 部门名称
     * @type {string}
     * @memberof UpdateOrgInput
     */
    name: string;
    /**
     * 部门编码
     * @type {string}
     * @memberof UpdateOrgInput
     */
    code?: string | null;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof UpdateOrgInput
     */
    status?: AvailabilityStatus;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof UpdateOrgInput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateOrgInput
     */
    remark?: string | null;
    /**
     * 部门Id
     * @type {number}
     * @memberof UpdateOrgInput
     */
    id?: number;
}
