/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface UpdateAlbumInput
 */
export interface UpdateAlbumInput {
    /**
     * 专辑名称
     * @type {string}
     * @memberof UpdateAlbumInput
     */
    name: string;
    /**
     * 专辑别名
     * @type {string}
     * @memberof UpdateAlbumInput
     */
    slug: string;
    /**
     * 封面图
     * @type {string}
     * @memberof UpdateAlbumInput
     */
    cover: string;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof UpdateAlbumInput
     */
    status?: AvailabilityStatus;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof UpdateAlbumInput
     */
    sort: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateAlbumInput
     */
    remark?: string | null;
    /**
     * 标签ID
     * @type {number}
     * @memberof UpdateAlbumInput
     */
    id: number;
}
