/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface UpdateCategoryInput
 */
export interface UpdateCategoryInput {
    /**
     * 分类名称
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    name?: string | null;
    /**
     * 分类别名
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    slug: string;
    /**
     * 父级id
     * @type {number}
     * @memberof UpdateCategoryInput
     */
    parentId?: number | null;
    /**
     * 封面图
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    cover?: string | null;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof UpdateCategoryInput
     */
    status?: AvailabilityStatus;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof UpdateCategoryInput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    remark?: string | null;
    /**
     * 分类ID
     * @type {number}
     * @memberof UpdateCategoryInput
     */
    id: number;
}
