/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddTagInput } from './add-tag-input';

/**
 *
 * @export
 * @interface UpdateTagInput
 */
export interface UpdateTagInput extends AddTagInput {
	/**
	 * 标签ID
	 * @type {number}
	 * @memberof UpdateTagInput
	 */
	id: number;
}
