/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
import { CoverType } from './cover-type';
/**
 * 
 * @export
 * @interface UpdateAlbumsInput
 */
export interface UpdateAlbumsInput {
    /**
     * 相册名称
     * @type {string}
     * @memberof UpdateAlbumsInput
     */
    name: string;
    /**
     * 封面图
     * @type {string}
     * @memberof UpdateAlbumsInput
     */
    cover: string;
    /**
     * 
     * @type {CoverType}
     * @memberof UpdateAlbumsInput
     */
    type?: CoverType;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof UpdateAlbumsInput
     */
    status?: AvailabilityStatus;
    /**
     * 排序值（值越小越靠前）
     * @type {number}
     * @memberof UpdateAlbumsInput
     */
    sort: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateAlbumsInput
     */
    remark?: string | null;
    /**
     * 是否可见
     * @type {boolean}
     * @memberof UpdateAlbumsInput
     */
    isVisible?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateAlbumsInput
     */
    id: number;
}
