/* tslint:disable */
/* eslint-disable */
/**
 * 博客后端接口
 * Dotnet9后端
 *
 * OpenAPI spec version: 0.0.1
 * Contact: 632871194@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
/**
 * 
 * @export
 * @interface UpdateCurrentUserInput
 */
export interface UpdateCurrentUserInput {
    /**
     * 姓名
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    name: string;
    /**
     * 
     * @type {Gender}
     * @memberof UpdateCurrentUserInput
     */
    gender?: Gender;
    /**
     * 昵称
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    nickName?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    birthday?: string | null;
    /**
     * 手机号码
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    mobile?: string | null;
    /**
     * 邮箱
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    email?: string | null;
}
