/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
import { MenuType } from './menu-type';
/**
 *
 * @export
 * @interface UpdateSysMenuInput
 */
export interface UpdateSysMenuInput {
	/**
	 * 菜单名称
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	name: string;
	/**
	 *
	 * @type {MenuType}
	 * @memberof UpdateSysMenuInput
	 */
	type?: MenuType;
	/**
	 * 权限编码
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	code?: string | null;
	/**
	 * 父级菜单
	 * @type {number}
	 * @memberof UpdateSysMenuInput
	 */
	parentId?: number | null;
	/**
	 * 路由名
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	routeName?: string | null;
	/**
	 * 路由地址
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	path?: string | null;
	/**
	 * 组件路径
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	component?: string | null;
	/**
	 * 重定向地址
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	redirect?: string | null;
	/**
	 * 菜单图标
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	icon?: string;
	/**
	 * 是否内嵌页面
	 * @type {boolean}
	 * @memberof UpdateSysMenuInput
	 */
	isIframe?: boolean;
	/**
	 * 外链地址
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	link?: string | null;
	/**
	 * 是否可见
	 * @type {boolean}
	 * @memberof UpdateSysMenuInput
	 */
	isVisible?: boolean;
	/**
	 * 是否缓存
	 * @type {boolean}
	 * @memberof UpdateSysMenuInput
	 */
	isKeepAlive?: boolean;
	/**
	 * 是否固定
	 * @type {boolean}
	 * @memberof UpdateSysMenuInput
	 */
	isFixed?: boolean;
	/**
	 *
	 * @type {AvailabilityStatus}
	 * @memberof UpdateSysMenuInput
	 */
	status?: AvailabilityStatus;
	/**
	 * 排序值（值越小越靠前）
	 * @type {number}
	 * @memberof UpdateSysMenuInput
	 */
	sort?: number;
	/**
	 * 备注
	 * @type {string}
	 * @memberof UpdateSysMenuInput
	 */
	remark?: string | null;
	/**
	 * 菜单/按钮Id
	 * @type {number}
	 * @memberof UpdateSysMenuInput
	 */
	id?: number;
}
