/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilityStatus } from './availability-status';
/**
 * 
 * @export
 * @interface UpdateSysRoleInput
 */
export interface UpdateSysRoleInput {
    /**
     * 角色名称
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    name: string;
    /**
     * 
     * @type {AvailabilityStatus}
     * @memberof UpdateSysRoleInput
     */
    status?: AvailabilityStatus;
    /**
     * 角色编码
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    code: string;
    /**
     * 排序值
     * @type {number}
     * @memberof UpdateSysRoleInput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    remark?: string | null;
    /**
     * 授权按钮菜单Id
     * @type {Array<number>}
     * @memberof UpdateSysRoleInput
     */
    menus: Array<number>;
    /**
     * 角色Id
     * @type {number}
     * @memberof UpdateSysRoleInput
     */
    id?: number;
}
