/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AlbumsOutput
 */
export interface AlbumsOutput {
  /**
   * 相册ID
   * @type {number}
   * @memberof AlbumsOutput
   */
  id?: number;
  /**
   * 相册名称
   * @type {string}
   * @memberof AlbumsOutput
   */
  name?: string | null;
  /**
   * 相册封面
   * @type {string}
   * @memberof AlbumsOutput
   */
  cover?: string | null;
  /**
   * 相册描述
   * @type {string}
   * @memberof AlbumsOutput
   */
  remark?: string | null;
  /**
   * 创建时间
   * @type {Date}
   * @memberof AlbumsOutput
   */
  createdTime?: Date;
}
