/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArticleBasicsOutput } from "./article-basics-output";
import { CreationType } from "./creation-type";
import { TagsOutput } from "./tags-output";
/**
 *
 * @export
 * @interface ArticleInfoOutput
 */
export interface ArticleInfoOutput {
  /**
   * 文章ID
   * @type {number}
   * @memberof ArticleInfoOutput
   */
  id?: number;
  /**
   * 标题
   * @type {string}
   * @memberof ArticleInfoOutput
   */
  title?: string | null;
  /**
   * 文章内容
   * @type {string}
   * @memberof ArticleInfoOutput
   */
  content?: string | null;
  /**
   * 封面图
   * @type {string}
   * @memberof ArticleInfoOutput
   */
  cover?: string | null;
  /**
   * 发布时间
   * @type {Date}
   * @memberof ArticleInfoOutput
   */
  publishTime?: Date;
  /**
   * 作者
   * @type {string}
   * @memberof ArticleInfoOutput
   */
  author?: string | null;
  /**
   * 浏览量
   * @type {number}
   * @memberof ArticleInfoOutput
   */
  views?: number;
  /**
   * 栏目ID
   * @type {number}
   * @memberof ArticleInfoOutput
   */
  categoryId?: number;
  /**
   * 点赞数量
   */
  praiseTotal?: number;
  /**
   * 当前用户是否已点赞
   */
  isPraise?: boolean;
  /**
   * 栏目名称
   * @type {string}
   * @memberof ArticleInfoOutput
   */
  categoryName?: string | null;
  /**
   *
   * @type {CreationType}
   * @memberof ArticleInfoOutput
   */
  creationType?: CreationType;
  /**
   * 是否允许评论
   * @type {boolean}
   * @memberof ArticleInfoOutput
   */
  isAllowComments?: boolean;
  /**
   * 是否是html
   * @type {boolean}
   * @memberof ArticleInfoOutput
   */
  isHtml?: boolean;
  /**
   * 是否置顶
   * @type {boolean}
   * @memberof ArticleInfoOutput
   */
  isTop?: boolean;
  /**
   * 转载链接
   * @type {string}
   * @memberof ArticleInfoOutput
   */
  link?: string | null;
  /**
   * 最后更新时间
   * @type {Date}
   * @memberof ArticleInfoOutput
   */
  updatedTime?: Date | null;
  /**
   *
   * @type {ArticleBasicsOutput}
   * @memberof ArticleInfoOutput
   */
  prev?: ArticleBasicsOutput;
  /**
   *
   * @type {ArticleBasicsOutput}
   * @memberof ArticleInfoOutput
   */
  next?: ArticleBasicsOutput;
  /**
   * 随机
   * @type {Array<ArticleBasicsOutput>}
   * @memberof ArticleInfoOutput
   */
  random?: Array<ArticleBasicsOutput> | null;
  /**
   * 标签
   * @type {Array<TagsOutput>}
   * @memberof ArticleInfoOutput
   */
  tags?: Array<TagsOutput> | null;
}
