/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogSetting } from './blog-setting';
import { BloggerInfo } from './blogger-info';
/**
 * 
 * @export
 * @interface BlogOutput
 */
export interface BlogOutput {
    /**
     * 
     * @type {BlogSetting}
     * @memberof BlogOutput
     */
    site?: BlogSetting;
    /**
     * 
     * @type {BloggerInfo}
     * @memberof BlogOutput
     */
    info?: BloggerInfo;
    /**
     * 各个页面封面图
     * @type {{ [key: string]: Array<string>; }}
     * @memberof BlogOutput
     */
    covers?: { [key: string]: Array<string>; } | null;
}
