/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BloggerInfo
 */
export interface BloggerInfo {
  /**
   * 头像
   * @type {string}
   */
  avatar: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof BloggerInfo
     */
    nikeName?: string | null;
    /**
     * QQ
     * @type {string}
     * @memberof BloggerInfo
     */
    qq?: string | null;
    /**
     * Github
     * @type {string}
     * @memberof BloggerInfo
     */
    github?: string | null;
    /**
     * 码云
     * @type {string}
     * @memberof BloggerInfo
     */
    gitee?: string | null;
    /**
     * 个性签名
     * @type {string}
     * @memberof BloggerInfo
     */
    motto?: string | null;
    /**
     * 关于我
     * @type {string}
     * @memberof BloggerInfo
     */
    about?: string | null;
}
