/* tslint:disable */
/* eslint-disable */
/**
 * 博客前端接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CoversOutput
 */
export interface CoversOutput {
    /**
     * 模块ID
     * @type {number}
     * @memberof CoversOutput
     */
    id?: number;
    /**
     * 模块名称
     * @type {string}
     * @memberof CoversOutput
     */
    name?: string | null;
    /**
     * 模块封面
     * @type {string}
     * @memberof CoversOutput
     */
    cover?: string | null;
    /**
     * 模块描述
     * @type {string}
     * @memberof CoversOutput
     */
    remark?: string | null;
    /**
     * 创建时间
     * @type {Date}
     * @memberof CoversOutput
     */
    createdTime?: Date;
}
