global using Dotnet9.CommonInitializer;
global using Dotnet9.Commons;
global using Dotnet9.Web.Service.BlogPosts;
global using Dotnet9.Web.ViewModel.BlogPosts;
global using Dotnet9.WebAPI.Domain.UserAdmin;
global using Dotnet9.WebAPI.Infrastructure;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
